import type { Deal, Watchlist, Alert, UserPreferences } from "@/lib/types/deal"

// Mock deals - realistic premium cabin deals from Australia
export const MOCK_DEALS: Deal[] = [
  {
    id: "mock-1",
    airline: "Qatar Airways",
    departure_city: "Sydney",
    departure_airport: "SYD",
    destination_city: "London",
    destination_airport: "LHR",
    cabin_class: "business",
    price_aud: 4899,
    original_price_aud: 8500,
    discount_percentage: 42,
    departure_date: "2026-06-15",
    return_date: "2026-07-01",
    is_return: true,
    booking_url: "https://www.qatarairways.com",
    deal_type: "mistake_fare",
    alliance: "oneworld",
    availability_count: 4,
    expires_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-2",
    airline: "Singapore Airlines",
    departure_city: "Melbourne",
    departure_airport: "MEL",
    destination_city: "Singapore",
    destination_airport: "SIN",
    cabin_class: "first",
    price_aud: 6200,
    original_price_aud: 12000,
    discount_percentage: 48,
    departure_date: "2026-05-20",
    return_date: "2026-06-05",
    is_return: true,
    booking_url: "https://www.singaporeair.com",
    deal_type: "sale",
    alliance: "star",
    availability_count: 2,
    expires_at: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-3",
    airline: "Emirates",
    departure_city: "Brisbane",
    departure_airport: "BNE",
    destination_city: "Dubai",
    destination_airport: "DXB",
    cabin_class: "business",
    price_aud: 5500,
    original_price_aud: 9000,
    discount_percentage: 39,
    departure_date: "2026-07-10",
    return_date: "2026-07-25",
    is_return: true,
    booking_url: "https://www.emirates.com",
    deal_type: "sale",
    alliance: "none",
    availability_count: 6,
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-4",
    airline: "Qantas",
    departure_city: "Perth",
    departure_airport: "PER",
    destination_city: "Los Angeles",
    destination_airport: "LAX",
    cabin_class: "business",
    price_aud: 7200,
    original_price_aud: 11000,
    discount_percentage: 35,
    departure_date: "2026-08-05",
    return_date: "2026-08-20",
    is_return: true,
    booking_url: "https://www.qantas.com",
    deal_type: "best_available",
    alliance: "oneworld",
    availability_count: 8,
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-5",
    airline: "ANA",
    departure_city: "Sydney",
    departure_airport: "SYD",
    destination_city: "Tokyo",
    destination_airport: "NRT",
    cabin_class: "business",
    price_aud: 3800,
    original_price_aud: 6500,
    discount_percentage: 42,
    departure_date: "2026-04-15",
    return_date: "2026-04-30",
    is_return: true,
    booking_url: "https://www.ana.co.jp",
    deal_type: "sale",
    alliance: "star",
    availability_count: 4,
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-6",
    airline: "Cathay Pacific",
    departure_city: "Melbourne",
    departure_airport: "MEL",
    destination_city: "Hong Kong",
    destination_airport: "HKG",
    cabin_class: "first",
    price_aud: 5100,
    original_price_aud: 10500,
    discount_percentage: 51,
    departure_date: "2026-05-01",
    return_date: "2026-05-15",
    is_return: true,
    booking_url: "https://www.cathaypacific.com",
    deal_type: "mistake_fare",
    alliance: "oneworld",
    availability_count: 2,
    expires_at: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-7",
    airline: "Thai Airways",
    departure_city: "Sydney",
    departure_airport: "SYD",
    destination_city: "Bangkok",
    destination_airport: "BKK",
    cabin_class: "business",
    price_aud: 2400,
    original_price_aud: 4200,
    discount_percentage: 43,
    departure_date: "2026-06-01",
    return_date: "2026-06-15",
    is_return: true,
    booking_url: "https://www.thaiairways.com",
    deal_type: "sale",
    alliance: "star",
    availability_count: 10,
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-8",
    airline: "Air France",
    departure_city: "Perth",
    departure_airport: "PER",
    destination_city: "Paris",
    destination_airport: "CDG",
    cabin_class: "business",
    price_aud: 5900,
    original_price_aud: 9500,
    discount_percentage: 38,
    departure_date: "2026-09-10",
    return_date: "2026-09-25",
    is_return: true,
    booking_url: "https://www.airfrance.com",
    deal_type: "sale",
    alliance: "skyteam",
    availability_count: 4,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-9",
    airline: "Qantas",
    departure_city: "Sydney",
    departure_airport: "SYD",
    destination_city: "Singapore",
    destination_airport: "SIN",
    cabin_class: "premium_economy",
    price_aud: 1800,
    original_price_aud: 2800,
    discount_percentage: 36,
    departure_date: "2026-05-10",
    return_date: "2026-05-20",
    is_return: true,
    booking_url: "https://www.qantas.com",
    deal_type: "best_available",
    alliance: "oneworld",
    availability_count: 12,
    created_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-10",
    airline: "Etihad",
    departure_city: "Melbourne",
    departure_airport: "MEL",
    destination_city: "London",
    destination_airport: "LHR",
    cabin_class: "first",
    price_aud: 8500,
    original_price_aud: 18000,
    discount_percentage: 53,
    departure_date: "2026-07-20",
    return_date: "2026-08-10",
    is_return: true,
    booking_url: "https://www.etihad.com",
    deal_type: "mistake_fare",
    alliance: "none",
    availability_count: 2,
    expires_at: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-11",
    airline: "Virgin Australia",
    departure_city: "Brisbane",
    departure_airport: "BNE",
    destination_city: "Los Angeles",
    destination_airport: "LAX",
    cabin_class: "business",
    price_aud: 6800,
    original_price_aud: 10500,
    discount_percentage: 35,
    departure_date: "2026-06-25",
    return_date: "2026-07-15",
    is_return: true,
    booking_url: "https://www.virginaustralia.com",
    deal_type: "sale",
    alliance: "none",
    availability_count: 6,
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-12",
    airline: "Japan Airlines",
    departure_city: "Sydney",
    departure_airport: "SYD",
    destination_city: "Tokyo",
    destination_airport: "NRT",
    cabin_class: "first",
    price_aud: 7500,
    original_price_aud: 15000,
    discount_percentage: 50,
    departure_date: "2026-04-01",
    return_date: "2026-04-15",
    is_return: true,
    booking_url: "https://www.jal.co.jp",
    deal_type: "points_redemption",
    alliance: "oneworld",
    points_required: 120000,
    points_currency: "Qantas Points",
    availability_count: 2,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Mock watchlists for demo user
export const MOCK_WATCHLISTS: Watchlist[] = [
  {
    id: "mock-watchlist-1",
    user_id: "demo-user",
    departure_city: "Sydney",
    destination_city: "London",
    cabin_classes: ["business", "first"],
    max_price_aud: 8000,
    flexible_dates: true,
    preferred_months: ["June", "July", "August"],
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-watchlist-2",
    user_id: "demo-user",
    departure_city: "Melbourne",
    destination_city: "Tokyo",
    cabin_classes: ["business"],
    max_price_aud: 5000,
    flexible_dates: true,
    preferred_months: ["April", "May", "October", "November"],
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-watchlist-3",
    user_id: "demo-user",
    departure_city: "Brisbane",
    destination_city: "Singapore",
    cabin_classes: ["business", "premium_economy"],
    max_price_aud: 3500,
    flexible_dates: false,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Mock alerts
export const MOCK_ALERTS: (Alert & { deals?: Deal; watchlists?: Watchlist })[] = [
  {
    id: "mock-alert-1",
    user_id: "demo-user",
    watchlist_id: "mock-watchlist-1",
    deal_id: "mock-1",
    alert_type: "new_deal",
    is_sent: false,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    deals: MOCK_DEALS[0],
    watchlists: MOCK_WATCHLISTS[0],
  },
  {
    id: "mock-alert-2",
    user_id: "demo-user",
    watchlist_id: "mock-watchlist-1",
    deal_id: "mock-10",
    alert_type: "price_drop",
    is_sent: false,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    deals: MOCK_DEALS[9],
    watchlists: MOCK_WATCHLISTS[0],
  },
  {
    id: "mock-alert-3",
    user_id: "demo-user",
    watchlist_id: "mock-watchlist-2",
    deal_id: "mock-5",
    alert_type: "new_deal",
    is_sent: true,
    sent_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    deals: MOCK_DEALS[4],
    watchlists: MOCK_WATCHLISTS[1],
  },
  {
    id: "mock-alert-4",
    user_id: "demo-user",
    watchlist_id: "mock-watchlist-3",
    deal_id: "mock-2",
    alert_type: "expiring_soon",
    is_sent: false,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    deals: MOCK_DEALS[1],
    watchlists: MOCK_WATCHLISTS[2],
  },
]

// Mock user preferences
export const MOCK_USER_PREFERENCES: UserPreferences = {
  user_id: "demo-user",
  email_notifications: true,
  notification_frequency: "instant",
  created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  updated_at: new Date().toISOString(),
}

// Demo mode flag - when true, app uses mock data
export const isDemoMode = () => {
  if (typeof window !== "undefined") {
    return localStorage.getItem("premium-deal-finder-demo") === "true"
  }
  return false
}

export const enableDemoMode = () => {
  if (typeof window !== "undefined") {
    localStorage.setItem("premium-deal-finder-demo", "true")
  }
}

export const disableDemoMode = () => {
  if (typeof window !== "undefined") {
    localStorage.removeItem("premium-deal-finder-demo")
  }
}
